apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ai=591234613960.dkr.ecr.us-east-1.amazonaws.com/ai-service
    argocd-image-updater.argoproj.io/ai.update-strategy: semver
    argocd-image-updater.argoproj.io/ai.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$  # ‚Üê FIXED
    argocd-image-updater.argoproj.io/write-back-method: argocd
    
spec:
  project: default
  source:
    repoURL: https://github.com/prasad-moru/GenAiStoreApp.git
    targetRevision: HEAD
    path: nginx-test-chart
    helm:
      releaseName: ai-service
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true